name: mmds-env
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip
  - pip:
    - numpy==1.23.5
    - pandas==1.5.3
    - scikit-learn==1.2.2
    - seaborn==0.12.2
    - ipykernel==6.25.2
    - sseclient==0.0.27
    - tqdm==4.65.0
    - yellowbrick==1.4
